### PR TITLE
Add blog post from Rodrigo Reghini Ferreira

### PR DESCRIPTION
**Pull request by eduardofiorezi**
ready to merge!

### CODE REVIEW

**Comment by beatrizcp87** [comment]
Is it ready?

**Comment by eduardofiorezi** [comment]
It's ready,, but i need to change de post date..

**Comment by eduardofiorezi** [comment]
@beatrizcp87 it's ok to merge.

**Comment by eduardofiorezi** [comment]
@beatrizcp87 i will merge :)

**Pull request merged**
